# Generated by Django 5.0.3 on 2025-12-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('pricing_policy', models.CharField(choices=[('internal', 'internal'), ('external', 'external')], default='internal', max_length=16)),
                ('edit_policy', models.CharField(choices=[('open', 'open'), ('locked', 'locked')], default='open', max_length=16)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('done', 'done'), ('failed', 'failed')], db_index=True, default='queued', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price_q', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='BRL', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(db_index=True, default='NEW', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omniman.channel')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('owner_type', models.CharField(blank=True, max_length=32, null=True)),
                ('owner_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(choices=[('open', 'open'), ('committed', 'committed'), ('abandoned', 'abandoned')], default='open', max_length=16)),
                ('pricing_policy', models.CharField(choices=[('internal', 'internal'), ('external', 'external')], default='internal', max_length=16)),
                ('edit_policy', models.CharField(choices=[('open', 'open'), ('locked', 'locked')], default='open', max_length=16)),
                ('rev', models.IntegerField(db_index=True, default=0)),
                ('items', models.JSONField(default=list)),
                ('data', models.JSONField(default=dict)),
                ('commit_token', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omniman.channel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('channel', 'session_key'), name='uniq_session_channel_key'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'open'), ('owner_type__isnull', False), ('owner_ref__isnull', False)), fields=('channel', 'owner_type', 'owner_ref'), name='uniq_open_session_owner'),
        ),
    ]
