# Generated by Django 5.0.3 on 2025-12-17 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniman', '0002_remove_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('display_order', 'id'), 'verbose_name': 'canal', 'verbose_name_plural': 'canais'},
        ),
        migrations.AlterModelOptions(
            name='directive',
            options={'verbose_name': 'diretiva', 'verbose_name_plural': 'diretivas'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at', 'id'), 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'sessão', 'verbose_name_plural': 'sessões'},
        ),
        migrations.AddField(
            model_name='directive',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='tentativas'),
        ),
        migrations.AddField(
            model_name='directive',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='disponível em'),
        ),
        migrations.AddField(
            model_name='directive',
            name='last_error',
            field=models.TextField(blank=True, default='', verbose_name='último erro'),
        ),
        migrations.AddField(
            model_name='directive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='BRL', max_length=3, verbose_name='moeda'),
        ),
        migrations.AddField(
            model_name='order',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='referência externa'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner_ref',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='referência do dono'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='tipo do dono'),
        ),
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(db_index=True, default='', max_length=64, verbose_name='chave da sessão'),
        ),
        migrations.AddField(
            model_name='order',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='snapshot'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_q',
            field=models.BigIntegerField(default=0, verbose_name='total (q)'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AddField(
            model_name='session',
            name='pricing',
            field=models.JSONField(blank=True, default=dict, verbose_name='precificação'),
        ),
        migrations.AddField(
            model_name='session',
            name='pricing_trace',
            field=models.JSONField(blank=True, default=list, verbose_name='trace de precificação'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='configuração'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordem de exibição'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='edit_policy',
            field=models.CharField(choices=[('open', 'aberta'), ('locked', 'bloqueada')], default='open', max_length=16, verbose_name='política de edição'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='pricing_policy',
            field=models.CharField(choices=[('internal', 'interna'), ('external', 'externa')], default='internal', max_length=16, verbose_name='política de preço'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='status',
            field=models.CharField(choices=[('queued', 'em fila'), ('running', 'em execução'), ('done', 'concluído'), ('failed', 'falhou')], db_index=True, default='queued', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='topic',
            field=models.CharField(db_index=True, max_length=64, verbose_name='tópico'),
        ),
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omniman.channel', verbose_name='canal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(max_length=64, unique=True, verbose_name='referência'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'novo'), ('IN_PROGRESS', 'em preparo'), ('READY', 'pronto'), ('COMPLETED', 'concluído'), ('CANCELED', 'cancelado')], db_index=True, default='NEW', max_length=32, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='session',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omniman.channel', verbose_name='canal'),
        ),
        migrations.AlterField(
            model_name='session',
            name='commit_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='token de commit'),
        ),
        migrations.AlterField(
            model_name='session',
            name='committed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fechada em'),
        ),
        migrations.AlterField(
            model_name='session',
            name='data',
            field=models.JSONField(default=dict, verbose_name='dados'),
        ),
        migrations.AlterField(
            model_name='session',
            name='edit_policy',
            field=models.CharField(choices=[('open', 'aberta'), ('locked', 'bloqueada')], default='open', max_length=16, verbose_name='política de edição'),
        ),
        migrations.AlterField(
            model_name='session',
            name='items',
            field=models.JSONField(default=list, verbose_name='itens'),
        ),
        migrations.AlterField(
            model_name='session',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='aberta em'),
        ),
        migrations.AlterField(
            model_name='session',
            name='owner_ref',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='referência do dono'),
        ),
        migrations.AlterField(
            model_name='session',
            name='owner_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='tipo do dono'),
        ),
        migrations.AlterField(
            model_name='session',
            name='pricing_policy',
            field=models.CharField(choices=[('internal', 'interna'), ('external', 'externa')], default='internal', max_length=16, verbose_name='política de preço'),
        ),
        migrations.AlterField(
            model_name='session',
            name='rev',
            field=models.IntegerField(db_index=True, default=0, verbose_name='revisão'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(max_length=64, verbose_name='chave da sessão'),
        ),
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.CharField(choices=[('open', 'aberta'), ('committed', 'fechada'), ('abandoned', 'abandonada')], default='open', max_length=16, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizada em'),
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64, verbose_name='escopo')),
                ('key', models.CharField(max_length=128, verbose_name='chave')),
                ('status', models.CharField(choices=[('in_progress', 'em andamento'), ('done', 'concluído'), ('failed', 'falhou')], default='in_progress', max_length=16, verbose_name='status')),
                ('response_code', models.IntegerField(blank=True, null=True, verbose_name='código de resposta')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='corpo da resposta')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'chave de idempotência',
                'verbose_name_plural': 'chaves de idempotência',
                'unique_together': {('scope', 'key')},
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=64, verbose_name='tipo')),
                ('actor', models.CharField(max_length=128, verbose_name='ator')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='omniman.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'evento do pedido',
                'verbose_name_plural': 'eventos do pedido',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=64, verbose_name='ID da linha')),
                ('sku', models.CharField(max_length=64, verbose_name='SKU')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='nome')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
                ('unit_price_q', models.BigIntegerField(verbose_name='preço unitário (q)')),
                ('line_total_q', models.BigIntegerField(verbose_name='total da linha (q)')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='omniman.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
            },
        ),
    ]
