# Generated by Django 6.0 on 2025-12-18 13:32

import omniman.models
from django.db import migrations, models


def migrate_status_values(apps, schema_editor):
    """Converte valores de status antigos para os novos canônicos."""
    Order = apps.get_model('omniman', 'Order')

    # Mapeamento: antigo -> novo
    STATUS_MAP = {
        'NEW': 'created',
        'IN_PROGRESS': 'processing',
        'DONE': 'completed',
        'CANCELLED': 'cancelled',
        # Valores já novos (idempotente)
        'created': 'created',
        'confirmed': 'confirmed',
        'processing': 'processing',
        'ready': 'ready',
        'dispatched': 'dispatched',
        'delivered': 'delivered',
        'completed': 'completed',
        'cancelled': 'cancelled',
        'returned': 'returned',
    }

    for old_status, new_status in STATUS_MAP.items():
        Order.objects.filter(status=old_status).update(status=new_status)


def reverse_status_values(apps, schema_editor):
    """Reverte para valores antigos (best effort)."""
    Order = apps.get_model('omniman', 'Order')

    # Mapeamento reverso: novo -> antigo
    REVERSE_MAP = {
        'created': 'NEW',
        'confirmed': 'NEW',
        'processing': 'IN_PROGRESS',
        'ready': 'IN_PROGRESS',
        'dispatched': 'IN_PROGRESS',
        'delivered': 'DONE',
        'completed': 'DONE',
        'cancelled': 'CANCELLED',
        'returned': 'CANCELLED',
    }

    for new_status, old_status in REVERSE_MAP.items():
        Order.objects.filter(status=new_status).update(status=old_status)


class Migration(migrations.Migration):

    dependencies = [
        ('omniman', '0005_rename_sessionline_to_sessionitem'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='session',
            managers=[
                ('objects', omniman.models.SessionManager()),
            ],
        ),
        # Primeiro converte os dados existentes
        migrations.RunPython(migrate_status_values, reverse_status_values),
        # Depois altera o campo com os novos choices
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'criado'), ('confirmed', 'confirmado'), ('processing', 'em preparo'), ('ready', 'pronto'), ('dispatched', 'despachado'), ('delivered', 'entregue'), ('completed', 'concluído'), ('cancelled', 'cancelado'), ('returned', 'devolvido')], db_index=True, default='created', max_length=32, verbose_name='status'),
        ),
    ]
