# Generated by Django 6.0 on 2025-12-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniman', '0008_rename_owner_to_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omniman.channel', verbose_name='canal de venda'),
        ),
        migrations.AlterField(
            model_name='order',
            name='handle_ref',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='order',
            name='handle_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='tipo de identificação'),
        ),
        migrations.AlterField(
            model_name='session',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omniman.channel', verbose_name='canal de venda'),
        ),
        migrations.AlterField(
            model_name='session',
            name='handle_ref',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='identificador'),
        ),
        migrations.AlterField(
            model_name='session',
            name='handle_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='tipo de identificação'),
        ),
    ]
