# Generated by Django 5.0.3 on 2026-01-20 01:04

import django.utils.timezone
import omniman.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniman', '0010_add_order_status_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directive',
            name='available_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='disponível em'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='payload',
            field=models.JSONField(blank=True, default=dict, encoder=omniman.models.DecimalEncoder, verbose_name='payload'),
        ),
        migrations.AlterField(
            model_name='order',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, encoder=omniman.models.DecimalEncoder, verbose_name='snapshot'),
        ),
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.CharField(choices=[('open', 'aberta'), ('committed', 'fechada'), ('abandoned', 'abandonada')], db_index=True, default='open', max_length=16, verbose_name='status'),
        ),
    ]
