# Generated by Django 5.2.11 on 2026-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniman', '0011_add_available_at_index'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessionitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='session_item_qty_positive'),
        ),
    ]
