# Generated by Django 5.2.11 on 2026-02-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniman', '0012_sessionitem_session_item_qty_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='directive',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='iniciado em'),
        ),
    ]
