# Generated by Django 5.2.11 on 2026-02-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniman', '0013_directive_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pendente'), ('in_progress', 'em andamento'), ('shipped', 'enviado'), ('delivered', 'entregue'), ('cancelled', 'cancelado')], db_index=True, default='pending', max_length=32, verbose_name='status')),
                ('tracking_code', models.CharField(blank=True, default='', max_length=128, verbose_name='código de rastreio')),
                ('tracking_url', models.URLField(blank=True, default='', verbose_name='URL de rastreio')),
                ('carrier', models.CharField(blank=True, default='', max_length=64, verbose_name='transportadora')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
            ],
            options={
                'verbose_name': 'fulfillment',
                'verbose_name_plural': 'fulfillments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FulfillmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
            ],
            options={
                'verbose_name': 'item do fulfillment',
                'verbose_name_plural': 'itens do fulfillment',
            },
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'line_id'), name='uniq_order_item_line_id'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='order_item_qty_positive'),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='omniman.order', verbose_name='pedido'),
        ),
        migrations.AddField(
            model_name='fulfillmentitem',
            name='fulfillment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='omniman.fulfillment', verbose_name='fulfillment'),
        ),
        migrations.AddField(
            model_name='fulfillmentitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_items', to='omniman.orderitem', verbose_name='item do pedido'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='fulfillment_item_qty_positive'),
        ),
    ]
