# Generated by Django 5.0.3 on 2026-01-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ref',
        ),
        migrations.DeleteModel(
            name='RefSequence',
        ),
    ]
